Fix/scripte bugs
technologiestiftung/qtrees-ai-data pull request #38
Opened 2023-06-12 14:38 UTC by birdMarcus

Im

2023-06-13 14:51 UTC, birdLova commented on infrastructure/database/templates/03_setup_tables.template.sql
> +FROM crosstab(
Die fehlt für Crosstab zu funktionieren:
CREATE EXTENSION tablefunc;

2023-06-13 15:23 UTC, birdLova requested changes
Zwei Sachen haben errors gebracht für mich: 
- trees.baumscheibe spalte fehlt für den public.vector_tiles materialized view 
- Fehlt extension für den sql crosstab function

2023-06-13 15:23 UTC, birdLova commented on infrastructure/database/templates/03_setup_tables.template.sql
> -    baumscheibe REAL
public.vector_tiles view braucht immer noch die Baumscheibe spalte : 

CREATE MATERIALIZED VIEW public.vector_tiles AS
SELECT
       .... 
	trees.street_tree AS trees_street_tree,
	trees.baumscheibe AS trees_baumscheibe,
Soll es noch da sein?

2023-06-14 09:32 UTC, birdLova commented on scripts/script_store_shading_index_in_db.py
> +  script_store_trees_in_db.py [--shadow_index_file=SHADOW_INDEX_FILE] [--shadow_index_file_interpolated=SHADOW_INDEX_FILE] [--db_qtrees=DB_QTREES]
Should this be: script_store_shading_index_in_db.py and not store trees?

2023-06-14 10:28 UTC, birdLova reviewed
Mir fehlt noch die shadow_index_file_interpolated.csv file.

2023-06-14 10:30 UTC, birdLova commented on infrastructure/database/templates/03_setup_tables.template.sql
> -    baumscheibe REAL
Erledigt - die public.vector_tiles kriegt die Baumscheibe spalte von qtrees_private

2023-06-14 17:22 UTC, birdLova reviewed
Ich habe alle Scripte nach ein paar kleine updates local erfolgreich laufen lassen, und ich habe in den Daten geguckt dass es mehr oder weniger in Ordnung aussieht. 

Ich habe also nicht in Detail die Scripte durchgeschaut, und auch nicht Scheduling/Ansible angeguckt.

- Readme 
Mir fehlt readme, wo man lesen kann in welche reinfolge die scripte durchgeführt werden sollen, und qtrees-private vs qtrees 

- MATERIALIZED VIEW public.vector_tiles 
Ist nur in dem script 'script_dummy_forecast' geupdatet, soll es auch nach dem script_nowcast_inference geupdatet werden? 

- Ich habe ein paar Files  ergänzt 
  -   Docker local file 
  -  vector_tiles view 
  -  extention zu dem DB 

Ich musste 3 Daten vom Drive herunterladen: 
- berlin_shadow_index_interpolated 
- tree_private 
 - watering

2023-06-16 10:32 UTC, birdMarcus commented
Have added important changes. Will do Readme later.

2023-06-16 10:32 UTC, merged